### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by SlickRed** [paddycarey/sofabuddy#8]
Create more in-depth and explanatory error messages for debugging.

**Comment by paddycarey** [comment]
script should now provide slightly more detailed error messages if a move problem is encountered

still need to add id error details

**Comment by SlickRed** [comment]
i would prefer error messages that gave the full pathname of any files, rather than just the filename. 

i know most of the time the script is only run on one folder, but with my crontab running it in lots of folders it would make it easier to track down problem files.
this would only be for "error" messages, not the move or identified messages.

**Comment by paddycarey** [comment]
more descriptive messages now for identify errors

**Comment by paddycarey** [comment]
now shows download_dir in errors if not default
