### ISSUE TITLE
Lock File

### ISSUE THREAD

**Issue by SlickRed** [paddycarey/sofabuddy#9]
I think this will probably stop happening once everything else is resolved, but every now and then I need to delete /tmp/tvwrangler_lock or the script won't run (Could not run tvwrangler.py: Locked).

**Comment by paddycarey** [comment]
CLOSED: This is the desired behaviour, script should remain locked if an error occurs which has not been tested for to avoid any unwanted effects. Need to find the error that is causing the script to remain locked.
